// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler View", function() {
    var view;
    this.collection = view = void 0;
    beforeEach(function() {
      this.collection = new Raffler.Collections.Entries();
      this.collection.fetch();
      return view = new Raffler.Views.EntriesIndex({
        collection: this.collection
      });
    });
    it("should have add function defined", function() {
      return expect(view.newName).toBeDefined();
    });
    it("should add new model to raffler view", function() {
      view.newName('Parth');
      return expect(this.collection.size()).toEqual(1);
    });
    it("should have function to set model to true", function() {
      return expect(view.setTrue).toBeDefined();
    });
    it("sets the model to true", function() {
      var item;
      item = this.collection.find(function(model) {
        this.model = model;
        return this.model.get("name") === 'Parth';
      });
      view.setTrue(item);
      return expect(item.get("winner")).toEqual(true);
    });
    it("should have save funciton defined", function() {
      return expect(view.saveModel).toBeDefined();
    });
    it("should have function to set model to false", function() {
      return expect(view.setFalse).toBeDefined();
    });
    it("sets the model to false", function() {
      var item;
      item = this.collection.find(function(model) {
        this.model = model;
        return this.model.get("name") === 'Parth';
      });
      view.setFalse(item);
      return expect(item.get("winner")).toEqual(false);
    });
    it("should have delete function defined", function() {
      return expect(view.delItem).toBeDefined();
    });
    return it("should delete model from raffler", function() {
      var item;
      item = this.collection.find(function(model) {
        this.model = model;
        return this.model.get("name") === 'Parth';
      });
      view.delItem(item);
      return expect(this.collection.size()).toEqual(0);
    });
  });

}).call(this);
